### ISSUE TITLE
Incorrect cursor position when reporting errors

### ISSUE THREAD

**Issue by frabert** [otac0n/Pegasus#82] opened 2016-02-16 19:07 UTC
When I try getting the cursor position for a syntax error (using exception.Data["cursor"]) I always get the last column on the last line, no matter where the error was detected

**Comment by otac0n** [comment] 2016-05-16 06:12
I'm not able to reproduce this problem.

Using the workbench, I can see the cursor being updated in this example:

Grammar:

    a = "a"* #ERROR{ "Here" }

Subject:

    aaaaaaaaaabaaaaaaaaaa

This reports an error on column 11:

![norepro](https://cloud.githubusercontent.com/assets/193584/15281708/7aa6aa9e-1af2-11e6-87fd-759b179ba4dc.png)

**Comment by otac0n** [comment] 2016-05-16 06:20
I'm closing this issue for now to keep things tidy, but if you have a repro case feel free to reopen.

**Closed by otac0n** 2016-05-16 06:20 UTC
