### ISSUE TITLE
Implement #{} to insert extra code at will

### ISSUE THREAD

**Issue by davidandl** [otac0n/Pegasus#75] opened 2015-12-17 05:36 UTC
The purpose is to insert arbitrary code into the generated parser at any point with no effect on the parse.

`#STATE{}` is bulky and manipulates the cursor state. All other code inserts require a return value.

The proposed `#{ code }` would allow insertion of arbitrary code anywhere and with no return value;

**Comment by otac0n** [comment] 2016-05-16 05:27
Out of curiosity, would this still be necessary if support for tracing (#71) were implemented?

If so, how would it be used?

**Comment by otac0n** [comment] 2016-05-16 05:55
I ask because the implementation will be an exact copy of `#STATE{}` except that it won't pass in the state as modifiable.  It will still be passed in so that users can inspect the cursor, so the "bulkyness" isn't really changed.

Based on these considerations, I really think that `#STATE` answers this need already.

**Comment by davidandl** [comment] 2016-05-16 10:19
What I actually do is to use &{} and enclose the code in a function that always returns true. I use this feature often (and #STATE never), eg for tracking block state, and for error handling. it is a minor but useful enhancement, unrelated to tracing.

**Comment by otac0n** [comment] 2016-07-25 23:04
I still don't understand how this is any different from a `#STATE{}` block.

As long as the code inside the state block doesn't mutate state, it behaves exactly the same as your proposed `#{}`.

With no other participation on this issue, I'm closing it to clean up the issues list.

**Closed by otac0n** 2016-07-25 23:04 UTC
Labels: enhancement, needs discussion

**Comment by davidandl** [comment] 2016-07-25 23:36
In support:

1.       It reduces the clutter of unnecessary STATE keywords

2.       It allows state mutation

3.       Since it is not available the alternative is to use &() guards and ensure that the called code returns true. This is misleading.

4.       It’s a small feature which you could implement easily and quickly.

 

But as always, your call. I’m just a user of your product. Do you have many others?

 

Regards

David M Bennett FACS

  _____  

Andl - A New Database Language - andl.org

**Comment by otac0n** [comment] 2016-07-26 01:57
The problem is, as you said, that `#{}` could be used to mutate state and mutating state via any mechanism other than `#STATE` is dangerous (due to back-tracking).

**Comment by davidandl** [comment] 2016-07-26 06:48
I understand the problem. One of the things I use this for is to set up a scope on block entry and finalise the scope on exit. There is no way to permit backtracking once a scope is entered, so I arrange the grammar to trigger an error if the parse fails beyond this point. Since any attempt to backtrack is fatal, manipulating state is perfectly safe.

 

This is another feature I would like: a grammar marker that triggers an error instead of backtracking. Some PEG parsers have that.

 

Regards

David M Bennett FACS

  _____  

Andl - A New Database Language - andl.org

**Comment by otac0n** [comment] 2016-08-01 15:37
I'm going to expand the syntax of `#state{}` expressions to allow simply `#{}` as mentioned in #43.  This satisfies this request almost exactly as requested.
