### ISSUE TITLE
brace in c# string

### ISSUE THREAD

**Issue by fsz1987** [otac0n/Pegasus#86] opened 2016-08-08 17:08 UTC
sorry about my poor English :sweat_smile:

I was using pegasus to build my text template engine.

I use a double brace to escape one of them, as following:

> br = '{{' { "{" }

but an error appeared:

> PEG0011 Unterminated code section

it seems the braces inside the code section must be paired. but I think a single brace inside a c# string expression should be legal

for now , I have to write like this to bypass this problem:

> br = '{{' { "\x007b" }

but it is really hard to read. so is this a bug ?

**Comment by otac0n** [comment] 2016-08-08 21:44
Hi, thanks for chiming in.

This is not exactly a bug, but it has been a known issue in Pegasus since the very beginning.  (Duplicate of #44)

You'll be happy to hear that I've recently integrated Roslyn into the Pegasus parser, allowing any valid C# to be used in a code section.  You can try out the latest release on NuGet, which should work as you expect: https://www.nuget.org/packages/Pegasus/4.0.0-alpha0035

**Closed by otac0n** 2016-08-08 21:44 UTC

**Comment by fsz1987** [comment] 2016-08-10 00:54
thanks, I'll try that
