### ISSUE TITLE
Implement parameterised rules

### ISSUE THREAD

**Issue by davidandl** [otac0n/Pegasus#70] opened 2015-12-08 05:34 UTC
The basic idea is to use the existing label syntax, but allow labels to be passed as parameters into a rule, where it can be used as a rule, or to replace a literal, or to pass into another rule.

IronMeta has this feature.

**Comment by otac0n** [comment] 2015-12-08 20:05
This is a duplicate of #32.

**Closed by otac0n** 2015-12-08 20:05 UTC

**Comment by davidandl** [comment] 2015-12-08 23:44
If you say so, but it was intended to be something much simpler.

    Rule1 = "foo" / Error("foo expected");
    Rule2 = "bar" / Error("bar expected");
    Error(m) = #STATE{ Error(m); } Skip;

Basically just a way to avoid some repetition.

**Comment by otac0n** [comment] 2015-12-17 03:07
It can't quite be that simple:

    Error ("foo expected")

This is ambiguous between a parameterized rule and a sequence.

**Comment by davidandl** [comment] 2015-12-17 05:23
So it would appear. The usual way of resolving this ambiguity is by significant whitespace.
```
Error ("foo expected") // sequence
Error("foo expected") // rule with parameter
```
The compiler will pick up any errors, assuming the rule either does or does not have a parameter.
